name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD=${PASSWORD}
          POSTGRES_DB=${DB_NAME}
          POSTGRES_USER=${DB_USER}
        options: >-
          --health-cmd "pg_isready -U ${DB_USER}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Docker Compose services
        run: |
          docker compose up --build -d

      - name: Wait for services to become healthy
        run: |
          docker compose ps &
          sleep 15
      - name: : Cypress Run
        uses: cypress-io/github-action@v4

      - name: Run Cypress Component Tests
        run: |
          docker compose run cypress npx cypress run --component

      - name: Run Cypress E2E Tests
        run: |
          docker compose run cypress npx cypress run --e2e

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker compose down --volumes

# docker compose up -d --build
# sleep 10
# docker compose run cypress
