name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose environment
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to become healthy
        run: |
          docker-compose ps
          sleep 30

      - name: Install dependencies
        run: docker-compose run cypress sh -c "rm -rf node_modules && npm ci"

      - name: Run Cypress Tests
        run: |
          docker-compose run --rm cypress

      - name: Stop and remove containers
        run: |
          docker-compose down
