name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Compose
        run: |
          docker-compose up -d database
          docker-compose up -d backend
          docker-compose up -d frontend

      - name: Wait for services to be ready
        run: |
          docker-compose exec database pg_isready -U ${{ secrets.DB_USER }}
          sleep 30

      - name: Run Cypress tests
        run: docker-compose run --rm cypress
# https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers
