name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Compose services
        run: |
          docker-compose -f docker-compose.yml build &
          sleep 10

      - name: Run Cypress E2E tests
        run: docker compose up --exit-code-from cypress

      - name: Shutdown Docker Compose
        run: docker-compose -f docker-compose.yml down # Clean up after the tests
