name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="bash -c 'pg_isready -U postgres'"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set secrets as environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install
      - name: Install Backend dependencies
        working-directory: backend
        run: |
          npm install
      - name: Build containers
        run: docker compose up --build -d

      - name: Wait for PostgreSQL to be ready
        run: |
          docker compose exec database pg_isready -U ${{ secrets.DB_USER }}
          sleep 30
      - name: Wait for frontend to be ready
        run: |
          npx wait-on http://localhost
      - name: Run tests
        run: docker compose up --exit-code-from cypress

        # Frontend dizinine geçip E2E testlerini çalıştırma
      - name: Run E2E tests
        run: |
          cd frontend && npm run dev &
          run: npm run test --spec 'cypress/e2e/**/*' # Kör E2E-tester
        env:
          CYPRESS_baseUrl: http://localhost

      # Component testlerini çalıştırma
      - name: Run Component Testing
        run: |
          cd frontend && npx cypress open --component # Component testlerini frontend dizininde çalıştırıyoruz
        env:
          CYPRESS_baseUrl: http://localhost

      - name: Stop and remove containers
        run: |
          docker compose down

# https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers
