name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Set up Docker Compose
        run: docker compose up -d # This will start your containers in the background
      - name: Build Docker Compose services
        run: docker compose build
      # docker compose up --build -d
      - name: Wait for services to become healthy
        run: |
          docker compose ps &
          sleep 30

      - name: Run Cypress E2E Tests
        run: |
          echo "Running Cypress E2E Tests"
          docker compose run cypress npx cypress run --e2e

     -  name: Run Cypress Component Tests
        run: |
           echo "Running Cypress Component Tests"
           docker compose run cypress npm ci
           docker compose run cypress npx cypress run --component

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker compose down --volumes
